# Generated by Django 4.1.6 on 2023-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="modify_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_counter",
            field=models.IntegerField(default=0),
        ),
    ]
